version: '3.8'
name: "gb_pv_capacity_model_dev_env"
services:
  jupyterlab:
    build: .
    ports:
      - "5000:5000"  # Port for JupyterLab
    volumes:
      - .:/gb_pv_capacity_model  # Mount local path to container path
    environment:
      JUPYTER_TOKEN: "gbpvcapacitymodel"
      
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow:/mlflow
    command: [ "mlflow", "server", "--backend-store-uri", "sqlite:////mlflow/mlflow.db", "--default-artifact-root", "/mlflow/artifacts", "--host", "0.0.0.0", "--port", "5000"]